version: '3.8'
services:
  game_recommender_ai_db:
    container_name: game_recommender_postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game_recommender_ai_db
    ports:
      - "5433:5432"
    volumes:
      - game_recommender_ai_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  game_recommender_ai_data: