version: '3.8'

name: game-recommender
services:
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [ playcure ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    container_name: backend
    build:
      context: ..
      dockerfile: services/backend/Dockerfile
      platforms:
        - linux/amd64
    depends_on:
      game_recommender_ai_db:
        condition: service_healthy
      ai-service:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - JAVA_OPTS=${JAVA_OPTS}
      - GRPC_AI_SERVICE_HOST=${GRPC_AI_SERVICE_HOST}
      - GRPC_AI_SERVICE_PORT=${GRPC_AI_SERVICE_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - REDIS_REDIS_URI=${REDIS_REDIS_URI}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
    ports:
      - "8080:8080"
    networks: [ playcure ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  ai-service:
    container_name: ai-service
    build:
      context: ..
      dockerfile: services/ai-service/Dockerfile
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - GRPC_PORT=${GRPC_PORT}
      - HTTP_PORT=${HTTP_PORT}
    ports:
      - "8000:8000"  # FastAPI health/metrics
      - "9090:9090"  # gRPC
    networks: [ playcure ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  game_recommender_ai_db:
    container_name: game-recommender-postgres-db
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    networks: [ playcure ]
    volumes:
      - game_recommender_ai_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  playcure:
    driver: bridge

volumes:
  game_recommender_ai_data:
  # Optional: persist data if needed
  # backend-data:
  # ai-service-data:
