version: '3.8'

services:
  ai-service:
    build: ../services/ai-service
    ports:
      - "9090:9090"
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
    networks:
      - game-recommender-network

  backend:
    build: ../services/backend
    ports:
      - "8080:8080"
    environment:
      - GRPC_AI_SERVICE_HOST=ai-service
      - GRPC_AI_SERVICE_PORT=9090
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - ai-service
      - redis
    networks:
      - game-recommender-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - game-recommender-network

volumes:
  redis_data:

networks:
  game-recommender-network:
    driver: bridge
