{
 "title": "Game recommender dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "1xx responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"1..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2xx responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"2..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3xx responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"3..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4xx responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"4..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response time (seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_sum[1m]))\r\n/\r\nsum by (uri) (rate(http_server_requests_seconds_count[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90 response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, uri) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Repository methods invocations per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by(method) (rate(spring_data_repository_invocations_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCES / ERROR status of repository invocation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by(state) (rate(spring_data_repository_invocations_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
   "targets": [
    {
     "expr": "sum by (method) (rate(spring_data_repository_invocations_seconds_sum[5m]) / \r\nrate(spring_data_repository_invocations_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}