version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: GR_prometheus
    ports:
      - 9999:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: GR_grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data: