# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reco.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nreco.proto\x12\x0fgamerecommender\"}\n\x15RecommendationRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bpreferences\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x11\n\tplatforms\x18\x04 \x03(\t\x12\x1b\n\x13max_recommendations\x18\x05 \x01(\x05\"\x8a\x01\n\x16RecommendationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12<\n\x0frecommendations\x18\x03 \x03(\x0b\x32#.gamerecommender.GameRecommendation\x12\x10\n\x08provider\x18\x04 \x01(\t\"\x99\x01\n\x12GameRecommendation\x12\r\n\x05title\x18\x01 \x01(\t\x12\r\n\x05genre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x17\n\x0fwhy_recommended\x18\x04 \x01(\t\x12\x11\n\tplatforms\x18\x05 \x03(\t\x12\x0e\n\x06rating\x18\x06 \x01(\x01\x12\x14\n\x0crelease_year\x18\x07 \x01(\t\"@\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"W\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x61i_response\x18\x03 \x01(\t\x12\x10\n\x08provider\x18\x04 \x01(\t2\xbb\x01\n\x16GameRecommenderService\x12\\\n\tRecommend\x12&.gamerecommender.RecommendationRequest\x1a\'.gamerecommender.RecommendationResponse\x12\x43\n\x04\x43hat\x12\x1c.gamerecommender.ChatRequest\x1a\x1d.gamerecommender.ChatResponseBL\n#ru.perevalov.gamerecommenderai.grpcP\x01Z#github.com/playcure/gamerecommenderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#ru.perevalov.gamerecommenderai.grpcP\001Z#github.com/playcure/gamerecommender'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=31
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=156
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=159
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=297
  _globals['_GAMERECOMMENDATION']._serialized_start=300
  _globals['_GAMERECOMMENDATION']._serialized_end=453
  _globals['_CHATREQUEST']._serialized_start=455
  _globals['_CHATREQUEST']._serialized_end=519
  _globals['_CHATRESPONSE']._serialized_start=521
  _globals['_CHATRESPONSE']._serialized_end=608
  _globals['_GAMERECOMMENDERSERVICE']._serialized_start=611
  _globals['_GAMERECOMMENDERSERVICE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
