{
 "title": "Database",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(r2dbc_pool_allocated_connections, instance)"
   },
   {
    "name": "name",
    "label": "Pool Name",
    "query": "label_values(r2dbc_pool_allocated_connections{instance=~\"$instance\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "JPA repository methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repository methods invocations per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method) (rate(spring_data_repository_invocations_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUCCES / ERROR status of repository invocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(state) (rate(spring_data_repository_invocations_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (method) (rate(spring_data_repository_invocations_seconds_sum[5m]) / \r\nrate(spring_data_repository_invocations_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connection pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "r2dbc_pool_allocated_connections{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "r2dbc_pool_idle_connections{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "r2dbc_pool_acquired_connections{instance=~\"$instance\",name=~\"$name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}